#pragma once
#include "Error.h"
#include "Parm.h"
#include "Log.h"
#include "In.h"
#include "LT.h"
#include "FST.h"
#include "IT.h"
#include "LexicalRecognizer.h"
#include "PolishNotation.h"
#include "GRB.h"
#include "MFST.h"
#include "Generation.h"

#include <TCHAR.H>
#include <iostream>
#include <locale>
#include <cwchar>
#include <string>